init 2023 rating
zafuacm/rating pull request #1
Opened 2023-06-28 07:15 UTC by smlwang

初始化 2023 赛季 rating

2023-06-28 12:48 UTC, rogeryoungh commented
1. 请不要修改无关的文件，一个 PR 只做一件事。
2. 2021、2022 赛季应当加上“模拟”或“非正式”等标注，以示不具有效性。

另外，每个赛季应当是 1 月还是 7 月开始，可以讨论一下。

2023-06-28 13:07 UTC, rogeryoungh commented
可以再补充一下 rating 具体的计算公式，还有其他的一些细节，比如初始分 6 场逐渐发放。

2023-06-29 11:18 UTC, rogeryoungh commented
你来看看还有什么问题。

2023-06-29 11:26 UTC, rogeryoungh requested changes

2023-06-29 11:26 UTC, rogeryoungh commented on README.md
> +比如：第一场给你 500 分，再加上第一场的表现分，最终加了 368 分，那么你实际的表现分是 -132 分。其他五场同理。
你这里写的啥，看不懂。表现分是专有名词吧，这里是不是使用不当。

2023-06-29 11:26 UTC, rogeryoungh commented on README.md
> +5. 为防止分数膨胀，引入 $inc$：
调整有两部分，一个是让所有人的 $\delta \to 0$，另一个是选取 $4 \sqrt{n}$ 的人，让他们的分数保持不变。

2023-06-29 12:59 UTC, smlwang commented on README.md
> +5. 为防止分数膨胀，引入 $inc$：
已调整成两部分

2023-06-29 13:01 UTC, smlwang reviewed
本地运行正常

2023-06-29 13:13 UTC, rogeryoungh approved these changes

2023-06-29 13:13 UTC, merged